<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'PhabricatorAuthProviderCas' => 'auth/PhabricatorAuthProviderCas.php',
    'PhutilAuthAdapterCas' => 'auth/PhutilAuthAdapterCas.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'PhabricatorAuthProviderCas' => 'PhabricatorAuthProvider',
    'PhutilAuthAdapterCas' => 'PhutilAuthAdapter',
  ),
));
